SET SEARCH_PATH TO public;
SELECT * FROM usuario;

ALTER TABLE usuario ALTER COLUMN contrasena TYPE VARCHAR(100);

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SIREP'
  AND TABLE_NAME = 'usuario';

  UPDATE usuario SET contrasena = '$2a$10$64ABE/ca4tjsO48ECV1CluXc/1YbOqNTgysMBQz8Vuxu741IqXA7C' WHERE usuario = 'maricarmen';
